# Generated by Django 5.2.4 on 2025-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="scholarship_pdfs/"
            ),
        ),
    ]
