# Generated by Django 5.2 on 2025-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0003_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
