# Generated by Django 5.2 on 2025-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0004_application_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
